<?php

/**
 * Chart of Accounts Seeder
 * 
 * This file contains sample chart of accounts data that can be used to populate
 * the database with standard accounting accounts.
 * 
 * Usage: You can either:
 * 1. Import this data through the API endpoints
 * 2. Create a seeder that uses this data
 * 3. Run SQL insert statements based on this structure
 */

return [
    // ===========================
    // ASSETS (1xxx)
    // ===========================
    [
        'code' => '1110',
        'name' => 'Cash in Bank',
        'description' => 'Main operating bank account',
        'type' => 'asset',
        'category' => 'current_asset',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '1115',
        'name' => 'Petty Cash',
        'description' => 'Small cash fund for minor expenses',
        'type' => 'asset',
        'category' => 'current_asset',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '1120',
        'name' => 'Accounts Receivable',
        'description' => 'Money owed by customers',
        'type' => 'asset',
        'category' => 'current_asset',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '1130',
        'name' => 'Inventory',
        'description' => 'Goods available for sale',
        'type' => 'asset',
        'category' => 'current_asset',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '1140',
        'name' => 'Prepaid Expenses',
        'description' => 'Expenses paid in advance',
        'type' => 'asset',
        'category' => 'current_asset',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '1145',
        'name' => 'Prepaid Insurance',
        'description' => 'Insurance premiums paid in advance',
        'type' => 'asset',
        'category' => 'current_asset',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '1150',
        'name' => 'Office Supplies',
        'description' => 'Office supplies inventory',
        'type' => 'asset',
        'category' => 'current_asset',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '1500',
        'name' => 'Equipment',
        'description' => 'Office and business equipment',
        'type' => 'asset',
        'category' => 'fixed_asset',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '1505',
        'name' => 'Vehicles',
        'description' => 'Company vehicles',
        'type' => 'asset',
        'category' => 'fixed_asset',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '1510',
        'name' => 'Furniture & Fixtures',
        'description' => 'Office furniture and fixtures',
        'type' => 'asset',
        'category' => 'fixed_asset',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '1515',
        'name' => 'Buildings',
        'description' => 'Company-owned buildings',
        'type' => 'asset',
        'category' => 'fixed_asset',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '1520',
        'name' => 'Land',
        'description' => 'Company-owned land',
        'type' => 'asset',
        'category' => 'fixed_asset',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '1550',
        'name' => 'Accumulated Depreciation - Equipment',
        'description' => 'Accumulated depreciation on equipment',
        'type' => 'asset',
        'category' => 'contra_asset',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],
    [
        'code' => '1555',
        'name' => 'Accumulated Depreciation - Vehicles',
        'description' => 'Accumulated depreciation on vehicles',
        'type' => 'asset',
        'category' => 'contra_asset',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],

    // ===========================
    // LIABILITIES (2xxx)
    // ===========================
    [
        'code' => '2110',
        'name' => 'Accounts Payable',
        'description' => 'Money owed to suppliers',
        'type' => 'liability',
        'category' => 'current_liability',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],
    [
        'code' => '2120',
        'name' => 'Accrued Expenses',
        'description' => 'Expenses incurred but not yet paid',
        'type' => 'liability',
        'category' => 'current_liability',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],
    [
        'code' => '2125',
        'name' => 'Salaries Payable',
        'description' => 'Salaries earned but not yet paid',
        'type' => 'liability',
        'category' => 'current_liability',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],
    [
        'code' => '2130',
        'name' => 'Unearned Revenue',
        'description' => 'Payment received for services not yet provided',
        'type' => 'liability',
        'category' => 'current_liability',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],
    [
        'code' => '2135',
        'name' => 'VAT Payable',
        'description' => 'Value Added Tax payable',
        'type' => 'liability',
        'category' => 'current_liability',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],
    [
        'code' => '2140',
        'name' => 'Income Tax Payable',
        'description' => 'Income tax payable',
        'type' => 'liability',
        'category' => 'current_liability',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],
    [
        'code' => '2500',
        'name' => 'Long-term Debt',
        'description' => 'Loans and debts due after one year',
        'type' => 'liability',
        'category' => 'long_term_liability',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],
    [
        'code' => '2510',
        'name' => 'Bank Loan',
        'description' => 'Bank loans payable',
        'type' => 'liability',
        'category' => 'long_term_liability',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],

    // ===========================
    // EQUITY (3xxx)
    // ===========================
    [
        'code' => '3100',
        'name' => 'Owner\'s Capital',
        'description' => 'Owner\'s investment in the business',
        'type' => 'equity',
        'category' => 'equity',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],
    [
        'code' => '3200',
        'name' => 'Owner\'s Drawings',
        'description' => 'Owner\'s withdrawals from the business',
        'type' => 'equity',
        'category' => 'equity',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '3900',
        'name' => 'Retained Earnings',
        'description' => 'Accumulated net income (auto-calculated)',
        'type' => 'equity',
        'category' => 'equity',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],

    // ===========================
    // REVENUE (4xxx)
    // ===========================
    [
        'code' => '4100',
        'name' => 'Sales Revenue',
        'description' => 'Revenue from product sales',
        'type' => 'revenue',
        'category' => 'operating_revenue',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],
    [
        'code' => '4200',
        'name' => 'Service Revenue',
        'description' => 'Revenue from services provided',
        'type' => 'revenue',
        'category' => 'operating_revenue',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],
    [
        'code' => '4300',
        'name' => 'Rental Income',
        'description' => 'Income from equipment/property rentals',
        'type' => 'revenue',
        'category' => 'operating_revenue',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],
    [
        'code' => '4900',
        'name' => 'Other Income',
        'description' => 'Miscellaneous income',
        'type' => 'revenue',
        'category' => 'other_revenue',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],
    [
        'code' => '4910',
        'name' => 'Interest Income',
        'description' => 'Interest earned on deposits',
        'type' => 'revenue',
        'category' => 'other_revenue',
        'normal_balance' => 'credit',
        'is_active' => true,
    ],

    // ===========================
    // EXPENSES (5xxx)
    // ===========================
    [
        'code' => '5100',
        'name' => 'Cost of Goods Sold',
        'description' => 'Direct cost of products sold',
        'type' => 'expense',
        'category' => 'cost_of_sales',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5200',
        'name' => 'Operating Expenses',
        'description' => 'General operating expenses',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5210',
        'name' => 'Internal Expense',
        'description' => 'Expenses for internal use of goods',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5300',
        'name' => 'Salaries Expense',
        'description' => 'Employee salaries and wages',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5310',
        'name' => 'Employee Benefits',
        'description' => 'Health insurance, retirement, etc.',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5400',
        'name' => 'Rent Expense',
        'description' => 'Office and facility rent',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5500',
        'name' => 'Utilities Expense',
        'description' => 'Electricity, water, gas, internet',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5510',
        'name' => 'Telephone Expense',
        'description' => 'Phone and communication costs',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5600',
        'name' => 'Depreciation Expense',
        'description' => 'Depreciation of fixed assets',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5700',
        'name' => 'Insurance Expense',
        'description' => 'Business insurance premiums',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5800',
        'name' => 'Office Supplies Expense',
        'description' => 'Office supplies used',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5810',
        'name' => 'Maintenance & Repairs',
        'description' => 'Equipment and facility maintenance',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5820',
        'name' => 'Fuel & Transportation',
        'description' => 'Vehicle fuel and transportation costs',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5830',
        'name' => 'Marketing & Advertising',
        'description' => 'Marketing and advertising costs',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5840',
        'name' => 'Professional Fees',
        'description' => 'Legal, accounting, consulting fees',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5850',
        'name' => 'Bank Charges',
        'description' => 'Bank fees and service charges',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5860',
        'name' => 'Bad Debt Expense',
        'description' => 'Uncollectible receivables',
        'type' => 'expense',
        'category' => 'operating_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5900',
        'name' => 'Interest Expense',
        'description' => 'Interest on loans and debts',
        'type' => 'expense',
        'category' => 'other_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
    [
        'code' => '5910',
        'name' => 'Tax Expense',
        'description' => 'Income tax expense',
        'type' => 'expense',
        'category' => 'other_expense',
        'normal_balance' => 'debit',
        'is_active' => true,
    ],
];
